Criação de itens na listagem (todo list)
mayaracaroline/todo-list pull request #1
Opened 2018-03-12 13:47 UTC by mayaracaroline

- [x] Campo para preencher o nome do novo item
- [x]  Label para o campo
- [x] Botão de adicionar item
- [x]  Evento de submit com enter
- [x]  Submit cria novo item na listagem, com o valor do campo de texto
- [x]  Limpar o campo de texto, após a criação
- [x]  Manter o foco no campo de texto, após a criação

2018-03-13 12:47 UTC, ggdaltoso requested changes

2018-03-13 12:47 UTC, ggdaltoso commented on index.html
> +			<!--<button name="btn"onclick="addItem()"> +</button>-->
Evite código comentado.
Tudo bem se fazê-los em desenvolvimento mas a master não deve ter código que não é executado.

2018-03-13 12:47 UTC, ggdaltoso commented on index.html
> +			<input type="submit" id="button-add-item" value="+" onclick="addItem()">
Toda tag HTML deve ser fechada para manter compatibilidade com XHTML
`<input />`

2018-03-13 12:47 UTC, ggdaltoso commented on index.html
> +				<label for="first-item" name="first-item">Meu primeiro item</label>
Um elemento `<label>` não precisa do atributo `for` caso o `input` esteja dentro dele, melhorando a organização e a leitura de código:

```
<label>
  <input type="checkbox" />
  Meu primeiro item
</label>
```

2018-03-13 12:47 UTC, ggdaltoso commented on index.html
> +	<footer>
Evite tags sem uso

2018-03-13 12:47 UTC, ggdaltoso commented on public/script.js
> +form.addEventListener('submit', onSubmit, false);
Ao invés de não fazer nada no `submit`, o que você acha de atribuir a função `addItem`?

Dessa forma, um item pode ser inserido na lista ao pressionar `Enter` além do click no botão `+`

2018-03-13 12:47 UTC, ggdaltoso commented on public/script.js
> +console.log(urlEncodeFormData(form));
Evite `logs` desnecessários na master

2018-03-13 12:47 UTC, ggdaltoso commented on public/script.js
> +function urlEncodeFormData(form) {
Evite funções que não são utilizadas além de sua declaração

2018-03-14 12:01 UTC, ddsilva requested changes

2018-03-14 12:01 UTC, ddsilva commented on index.html
> +			<input type="text" name="input-add-item" id="input-add-item"  placeholder="Your text here" autofocus>
💅 
Por questões de legibilidade, sugiro que você quebre os atributos de tags que ficam com a linha grande assim.

Ficaria dessa forma:

```html
<input 
  type="text" 
  name="input-add-item" 
  id="input-add-item"  
  placeholder="Your text here" 
  autofocus
/>
```

2018-03-14 12:01 UTC, ddsilva commented on index.html
> +	<footer>
Sim, está vazia.

2018-03-14 12:01 UTC, ddsilva commented on public/script.js
> +var btnAddItem = document.getElementById("button-add-item");
O que acha de colocar o código desse arquivo dentro de uma [IIFE](https://developer.mozilla.org/pt-BR/docs/Glossario/IIFE)?

Ex:

```js
(function() {
  // código aqui
})();
```

Isso fecha o escopo de sua aplicação e evita conflito de variáveis globais.

2018-03-14 12:01 UTC, ddsilva commented on public/script.js
> +	var valueInput = document.getElementById("input-add-item").value;
É aconselhável criar variáveis apenas quando for preciso retulizar o valor, mais de uma vez.
Nesse caso, como o valor só é usado em um momento, recomenda-se que seja atribuido diretamente, quando for utilizado:

```js
 label.innerHTML = document.getElementById("input-add-item").value;
```

A exeção é quando uma refatoração for necessária, para reduzir a complexidade do código ou o tamanho de uma linha, dividindo as etapas. Ou quando o valor só é acessível dentro de um escopo e precisa ser usado em outro. Nesse caso, o uso de uma variável que vai ser utilizada só uma vez, é válido.

2018-03-14 12:01 UTC, ddsilva commented on public/script.js
> +form.addEventListener('submit', onSubmit, false);
Eu colocaria a chamada de `addItem` dentro de `onSubimit`. 
Pois acredito que a responsabilidade de evitar o subimit do formulário (` event.preventDefault()`) não é de `addItem`, mas só de `onSubimit`.

Ficaria assim: 
```js
function addItem(){ 
  // code 
}

function onSubmit(event) {
  event.preventDefault();
  addItem();
}

form.addEventListener('submit', onSubmit);
```

E tiraria o `addItem` do `onClick` do botão pra ser chamado no submit dor formulário, que é disparado com enter e com clique.

O que você acha, @ggdaltoso?

2018-03-14 12:01 UTC, ddsilva commented on public/script.js
> +form.addEventListener('submit', onSubmit, false);
Outro ponto: O `false` no terceiro parâmetro é necessário?

Ele diz respeito a captura de eventos em cascata, que vem de componentes filhos. `False` já é o valor padrão. Se não é alterado, não precisa ser especificado, certo?

2018-03-14 12:01 UTC, ddsilva commented on public/script.js
> +form.submit = onSubmit;
Por que essa atribuição é necessária?

2018-03-14 13:38 UTC, nuncaesqueca commented on index.html
> +		<form id="form-add-item" action="">
Quão legal seria se dentro do <form> existissem os elementos <fieldset>, <legend> ?

Esses carinhas são uma forma bem legal de criar grupos que compartilham a mesma finalidade, o fieldset agrupa e o legend rotula, além da semântica, isso é muito legal pelo lado da acessibilidade - a maioria das tecnlogias assistivas como por exemplo leitores de tela, vão pronunciar o contéudo primeiro do legend e depois dos labels.

``` html
<form id="form-add-item" action="">
  <fieldset>
    <legend>My to-do list</legend>

    <label>
      <input type="text" name="input-add-item" id="input-add-item"  placeholder="Your text here" autofocus>
      Insert you task
    </label>

    <input type="submit" id="button-add-item" value="+" onclick="addItem()"> 
  </fieldset>
</form>
```

2018-03-15 12:15 UTC, ddsilva commented on index.html
> +		    </li>
Acredito que a indentação deu errado aqui.

2018-03-15 12:34 UTC, ddsilva commented on public/script.js
> +(function(){var btnAddItem = document.getElementById("button-add-item");
Sugiro que vc faça uma indentação dentro dessa função :)

2018-03-15 13:31 UTC, ddsilva approved these changes

2018-03-15 13:38 UTC, ggdaltoso approved these changes

2018-03-15 13:43 UTC, merged