Style
mayaracaroline/todo-list pull request #3
Opened 2018-04-19 11:17 UTC by mayaracaroline

- [x] Definir qual será o estilo
- [x] Aplicar o estilo nos checkboxes
- [x] Aplicar o estilo na listagem
- [x] Aplicar o estilo no botão de remoção dos concluídos
- [x] Aplicar o estilo no formulário
- [x] Validar as resoluções

2018-04-19 12:31 UTC, allyssonsantos commented on index.html
> +<html class="no-js" lang="">
Seria legal você colocar o valor "pt-BR" no atributo "lang", esse atributo serve pra dizer para o browser em qual idioma essa página está, isso ajuda com que os leitores de tela pronunciem as palavras corretamente. Você pode utilizar esse atributo em qualquer tag HTML.

2018-04-19 12:35 UTC, ggdaltoso requested changes

2018-04-19 12:35 UTC, ggdaltoso commented on public/style.css
> +    border: solid #e91e63 2px;
Para `border`, siga a regra `width | style | color`, como é visto no [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/border).

2018-04-19 12:35 UTC, ggdaltoso commented on public/script.js
> +        checkboxList = ul.querySelectorAll('input');
Declare as variáveis antes de usá-las.

2018-04-19 12:35 UTC, ggdaltoso commented on public/script.js
> +    var liList = ul.querySelectorAll('li');
Dê nomes mais contextualizados às suas variáveis. 

Nesse caso, o que é `liList`? 
Seria a lista de Itens? Se sim, `itemList` seria mais conveniente.

2018-04-19 12:35 UTC, ggdaltoso commented on public/script.js
> +          checkboxList = ul.querySelectorAll('input');
Ao invés de pegar novamente a referencia para o DOM, você poderia usar a referência para a lista de itens, declarada ali em cima como `liList`.

2018-04-19 12:36 UTC, ggdaltoso commented on public/script.js
> +        appendChild(
:+1:

2018-04-19 13:17 UTC, mayaracaroline commented on public/script.js
> +          checkboxList = ul.querySelectorAll('input');
Não dá, porque de qualquer forma teria que atualizar a variável com o valor atual de LI existentes.
Dá pra fazer direto no "if":

if(ul.querySelectorAll('li').length == 0){
            btnRemover.style.display = "none";           
          }

2018-04-19 13:26 UTC, mayaracaroline commented on index.html
> +<html class="no-js" lang="">
Boa,  esqueci só o principal kkkk

2018-04-19 13:27 UTC, mayaracaroline commented on public/script.js
> +        checkboxList = ul.querySelectorAll('input');
Muito bem lembrado =D kkk

2018-04-19 13:36 UTC, ddsilva requested changes

2018-04-19 13:36 UTC, ddsilva commented on public/script.js
> +  	label.appendChild(checkbox);
:nail_care: 

Espaços a mais na identação :smile:

2018-04-19 13:36 UTC, ddsilva commented on public/script.js
> +  	ul.appendChild(li);
:nail_care: 
Identação :)

2018-04-19 13:36 UTC, ddsilva commented on public/script.js
> +      if (confirm("Deseja excluir estes itens?")) {
Aqui você pode juntar as duas condições em um `if` só. Diminui a identação e reduz a complexidade. Ficaria assim:

```javascript
if(verificaCheckList(checkboxList) && confirm("Deseja excluir estes itens?")){
  // code...
}
```

2018-04-19 13:42 UTC, allyssonsantos commented on public/script.js
> +  // Função: validateEmptyInput()
Acho uma boa sempre comentar o que cada função faz. Existe um padrão pra escrever esses comentários que se chama "JsDoc", acho que você poderia dar uma olhada e começar a adotar nos seus projetos. É bem legal

2018-04-19 13:51 UTC, allyssonsantos commented on public/style.css
> +@import url('https://fonts.googleapis.com/css?family=Great+Vibes|Roboto');
Evite utilizar "@import" de css pois isso pode prejudicar a performance de renderização. Utilizando "@import" o browser não irá fazer a requisição em paralelo. Se você colocasse como uma tag <link ...> no seu HTML o browser iria iniciar o download dos dois arquivos ao mesmo tempo.

2018-04-19 13:52 UTC, allyssonsantos commented on public/style.css
> +  border-bottom: solid 3px  #e91e63;
Tem dois espacinhos depois do "3px"

2018-04-25 18:55 UTC, ggdaltoso approved these changes

2018-04-26 12:54 UTC, alan-oliv approved these changes

2018-05-02 11:10 UTC, ddsilva commented on public/script.js
> +  function verificaCheckList(checkList) {
it's a good practice to use only one language for var names. English or Portuguese.

2018-05-02 11:34 UTC, ddsilva approved these changes

2018-05-02 12:01 UTC, merged